language: objective-c
xcode_project: PromiseKit.xcodeproj
xcode_scheme: [PMKiOS, PMKmacOS]
xcode_sdk: [iphonesimulator10.0, macosx10.11]
osx_image: xcode8

install:
  - "gem install travis-xcodebuild"
  - "carthage bootstrap --platform Mac,iOS"

script:
  - travis-xcodebuild

matrix:
  exclude:
    - xcode_scheme: PMKmacOS
      xcode_sdk: iphonesimulator10.0
    - xcode_scheme: PMKiOS
      xcode_sdk: macosx10.11

branches:
  only:
    - master
    - swift-2.3
    - swift-2.2-minimal-changes
    - swift-2.0-minimal-changes
    - legacy-1.x
